# Generated by Django 3.0.14 on 2022-10-07 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modofiedAt', models.DateField(auto_created=True, auto_now=True)),
                ('createdAt', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('street', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('finish', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentications.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modofiedAt', models.DateField(auto_created=True, auto_now=True)),
                ('createdAt', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('moneySpent', models.IntegerField()),
                ('moneyDonated', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.VolunteerDay')),
            ],
        ),
        migrations.CreateModel(
            name='gadeget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modofiedAt', models.DateField(auto_created=True, auto_now=True)),
                ('createdAt', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modofiedAt', models.DateField(auto_created=True, auto_now=True)),
                ('createdAt', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modofiedAt', models.DateField(auto_created=True, auto_now=True)),
                ('createdAt', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
